fixtures:
  forge_modules:
    concat:
      repo: "puppetlabs/apache"
      ref: "9.1.3"
    concat:
      repo: "puppetlabs/concat"
      ref: "8.0.1"
    concat:
      repo: "puppet/epel"
      ref: "4.1.0"
    concat:
      repo: "puppetlabs/postgresql"
      ref: "9.0.3"
    concat:
      repo: "puppetlabs/stdlib"
      ref: "8.6.0"
    concat:
      repo: "puppetlabs/vcsrepo"
      ref: "6.0.1"
  symlinks:
    redmine: "#{source_dir}"
